### ISSUE TITLE
source model

### ISSUE THREAD

**Issue by xushuojie** [caixin1998/UnReGA#1]
可以提供一下source model ckpts吗，代码中似乎没有source model的训练代码

**Comment by caixin98** [comment]
The xgaze-trained checkpoints and the enhanced MPIIRes datasets are available at https://drive.google.com/drive/folders/1f4pGXCgxzbMeZmArlDo2d3ysW6K9sHnx?usp=drive_link.

**Comment by xushuojie** [comment]
谢谢！Thank you!

**Comment by xushuojie** [comment]
> The xgaze-trained checkpoints and the enhanced MPIIRes datasets are available at https://drive.google.com/drive/folders/1f4pGXCgxzbMeZmArlDo2d3ysW6K9sHnx?usp=drive_link.
这两个MPIIRes.zip和MPIIFaceGaze.tar.gz压缩包不完整，内容有缺失。😭
The two MPIIRes.zip and MPIIFaceGaze.tar.gz zip archives are incomplete and have missing content.

**Comment by caixin98** [comment]
> > The xgaze-trained checkpoints and the enhanced MPIIRes datasets are available at https://drive.google.com/drive/folders/1f4pGXCgxzbMeZmArlDo2d3ysW6K9sHnx?usp=drive_link.
> > 这两个MPIIRes.zip和MPIIFaceGaze.tar.gz压缩包不完整，内容有缺失。😭
> > The two MPIIRes.zip and MPIIFaceGaze.tar.gz zip archives are incomplete and have missing content.

Please check the updated files.

**Comment by xushuojie** [comment]
> > > The xgaze-trained checkpoints and the enhanced MPIIRes datasets are available at https://drive.google.com/drive/folders/1f4pGXCgxzbMeZmArlDo2d3ysW6K9sHnx?usp=drive_link.
> > > 这两个MPIIRes.zip和MPIIFaceGaze.tar.gz压缩包不完整，内容有缺失。😭
> > > The two MPIIRes.zip and MPIIFaceGaze.tar.gz zip archives are incomplete and have missing content.
> 
> Please check the updated files.

Okay, thank you for your work
